/* Original travel instructions. Factual corrections cite the individual record;
 * provisional routes never promote Classic details to verified Forever facts. */
(function(root) {
  'use strict';
  const version = '2026-10-07.1';
  // Content-addressed steps survive reordering/insertion. Rewritten instructions
  // become new steps; old completions remain in the export, never transfer by index.
  function stepId(prefix,text){let hash=2166136261;for(const ch of text)hash=Math.imul(hash^ch.charCodeAt(0),16777619);return prefix+'-'+(hash>>>0).toString(16);}
  const source = id => `https://www.wowhead.com/forever/quest=${id}`;
  const place = (npc, zone, coordinates = null, confidence = 'provisional') => ({npc, zone, coordinates, confidence});
  const additions = [
    {id:886,name:'The Barrens Oases',faction:'Horde',dungeons:['wailing-caverns'],role:'chain-unresolved',chainUnresolved:true,eligibilityUnresolved:true,turnIn:place('Tonga Runetotem','The Crossroads',null,'verified'),objectives:'Speak to Tonga before starting the oasis investigation, if this breadcrumb is offered.',notes:['Breadcrumb availability, racial restrictions and pickup location differ in reference material. Do not treat it as a mandatory prerequisite for The Forgotten Pools.']},
    {id:5724,name:'Returning the Lost Satchel',minLevel:9,questLevel:16,faction:'Horde',dungeons:['ragefire-chasm'],role:'followup',starter:'inside',prerequisites:[5722],pickup:place('Maur Grimtotem','Ragefire Chasm'),turnIn:place('Rahauro','Thunder Bluff',[70,30]),requiredItems:['Grimtotem Satchel'],objectives:'Deliver the recovered satchel to Rahauro.',observed:true},
    {id:5727,name:'Hidden Enemies',minLevel:9,questLevel:12,faction:'Horde',dungeons:['ragefire-chasm'],role:'prerequisite',prerequisites:[5726],pickup:place('Thrall','Orgrimmar',[31,37]),turnIn:place('Thrall','Orgrimmar',[31,37]),requiredItems:["Lieutenant's Insignia"],objectives:'Speak with Neeru while carrying the insignia, then return to Thrall.'},
    {id:5729,name:'Hidden Enemies',minLevel:9,questLevel:16,faction:'Horde',dungeons:['ragefire-chasm'],role:'followup',prerequisites:[5728],pickup:place('Thrall','Orgrimmar'),turnIn:place('Neeru Fireblade','Orgrimmar'),objectives:'After reporting the dungeon kills, speak with Neeru.'},
    {id:5730,name:'Hidden Enemies',minLevel:9,questLevel:16,faction:'Horde',dungeons:['ragefire-chasm'],role:'followup',prerequisites:[5729],pickup:place('Neeru Fireblade','Orgrimmar'),turnIn:place('Thrall','Orgrimmar'),objectives:'Return to Thrall for the chain reward.'},
    {id:877,name:'The Stagnant Oasis',minLevel:10,questLevel:16,faction:'Horde',dungeons:['wailing-caverns'],role:'prerequisite',prerequisites:[870],pickup:place('Tonga Runetotem','The Crossroads'),objectives:'Continue the oasis investigation; confirm the current beta sequence with Tonga.',chainUnresolved:true},
    {id:880,name:'Altered Beings',minLevel:10,questLevel:16,faction:'Horde',dungeons:['wailing-caverns'],role:'prerequisite',prerequisites:[877],pickup:place('Tonga Runetotem','The Crossroads'),chainUnresolved:true},
    {id:1489,name:'Hamuul Runetotem',minLevel:10,questLevel:16,faction:'Horde',dungeons:['wailing-caverns'],role:'prerequisite',prerequisites:[880],pickup:place('Tonga Runetotem','The Crossroads'),turnIn:place('Hamuul Runetotem','Thunder Bluff'),observed:true},
    {id:1490,name:'Nara Wildmane',minLevel:10,questLevel:16,faction:'Horde',dungeons:['wailing-caverns'],role:'prerequisite',prerequisites:[1489],pickup:place('Hamuul Runetotem','Thunder Bluff'),turnIn:place('Nara Wildmane','Thunder Bluff'),observed:true},
    {id:92753,name:'Destruction in Deadmines',minLevel:null,questLevel:18,faction:'Alliance',raceMask:'4294967372',dungeons:['deadmines'],prerequisites:[92752],pickup:place('Alba Fairmoon','Westfall'),turnIn:place('Alba Fairmoon','Deadmines back exit'),requiredItems:['Extra-Destructive Explosives'],objectives:'Place the supplied explosives at the forge. Leave through the back exit and meet Alba before using your hearthstone.',observed:true,notes:['Race mask excludes Human in the inspected record; Skyborne mask mapping is unverified.']},
    {id:92742,name:'Testing the Wells',faction:'Alliance',dungeons:['deadmines'],role:'prerequisite',raceMask:'4294967372',pickup:place('Alba Fairmoon','Westfall'),requiredItems:['Well Water Sample Kit'],objectives:'Sample the Jansen Stead and Molsen Farm wells; return to Alba.',chainUnresolved:true},
    {id:92744,name:'Murloc Gills',faction:'Alliance',dungeons:['deadmines'],role:'prerequisite',raceMask:'4294967372',prerequisites:[92742],pickup:place('Alba Fairmoon','Westfall'),objectives:'Collect seven Longshore Murloc Gills while questing along the coast.'},
    {id:92745,name:'The State of the Mines',faction:'Alliance',dungeons:['deadmines'],role:'prerequisite',raceMask:'4294967372',prerequisites:[92744],pickup:place('Alba Fairmoon','Westfall'),objectives:'Visit Jangolode Mine and Gold Coast Quarry for the required miner kills.'},
    {id:92747,name:'Moonbrook Espionage',faction:'Alliance',dungeons:['deadmines'],role:'prerequisite',raceMask:'4294967372',prerequisites:[92745],pickup:place('Alba Fairmoon','Westfall'),chainUnresolved:true,notes:['Continue Explosive Consultation → A Dynamite Plan → both Detonation at a Distance stages. Those intermediate IDs/pickups are unresolved; do not skip them.']},
    {id:92751,name:'Detonation at a Distance',faction:'Alliance',dungeons:['deadmines'],role:'prerequisite',raceMask:'4294967372',chainUnresolved:true,notes:['Intermediate prerequisite records are unresolved.']},
    {id:92752,name:'Explosive Consultation',faction:'Alliance',dungeons:['deadmines'],role:'prerequisite',raceMask:'4294967372',prerequisites:[92751],pickup:place('Alba Fairmoon','Westfall')}
  ];
  const corrections = {
    5722:{pickup:place('Rahauro','Thunder Bluff',[70,30]),turnIn:place('Maur Grimtotem','Ragefire Chasm'),starter:'npc',objectives:'Find Maur before leaving the trogg area; complete this stage at his body and accept Returning the Lost Satchel.',notes:['The inventory confuses this pickup with the inside-instance follow-up. Corrected using the individual quest series.']},
    5726:{minLevel:9,questLevel:12,faction:'Horde',role:'prerequisite',dungeons:['ragefire-chasm'],pickup:place('Thrall','Orgrimmar',[31,37]),turnIn:place('Thrall','Orgrimmar'),chainUnresolved:false,objectives:"Obtain a Lieutenant's Insignia from Burning Blade enemies in Skull Rock, then return to Thrall.",notes:['Classic-location fallback: confirm the beta objective before leaving Orgrimmar.']},
    5728:{prerequisites:[5727],chainUnresolved:false,objectives:'Kill Bazzalan and Jergosh. Report to Thrall, then finish the two city dialogue stages.',turnIn:place('Thrall','Orgrimmar')},
    5761:{objectives:"Loot Taragaman's heart and return it to Neeru.",turnIn:place('Neeru Fireblade','Orgrimmar')},
    5725:{objectives:'Collect both required books from Searing Blade enemies.',turnIn:place('Varimathras','Undercity')},
    5723:{objectives:'Kill eight Ragefire Troggs and eight Ragefire Shamans.',turnIn:place('Rahauro','Thunder Bluff')},
    96391:{minLevel:null,faction:'Alliance',role:'prerequisite',dungeons:['hall-of-thanes'],starter:'item',requiredItems:['Dark Iron Map'],pickup:place(null,'Dun Morogh'),turnIn:place('Earthseer Farsen','Dun Morogh'),chainUnresolved:true,notes:['The series confirms Underground Map precedes Incursion. Drop eligibility and pickup minimum still need verification.']},
    96393:{prerequisites:[96391],chainUnresolved:false,turnIn:place('King Magni Bronzebeard','Ironforge',null,'verified'),notes:['Corrected chain direction from the individual Forever series.']},
    96394:{pickup:place('Afadra Dunwall','Old Ironforge'),notes:['Published coordinates duplicate the outdoor Farsen location; withheld until verified.']},
    98423:{starter:'inside',notes:['Inspect the Reliquary of Kings vault. Turn-in and subsequent treaty stages are unresolved.']},
    865:{minLevel:13,questLevel:18,faction:'Both',role:'prerequisite',dungeons:['wailing-caverns'],pickup:place('Mebok Mizzyrix','Ratchet',[62,37]),turnIn:place('Mebok Mizzyrix','Ratchet'),chainUnresolved:false,objectives:'Collect raptor horns during Barrens leveling before requesting Smart Drinks.'},
    1491:{prerequisites:[865],chainUnresolved:false,turnIn:place('Mebok Mizzyrix','Ratchet')},
    870:{minLevel:10,questLevel:13,faction:'Horde',role:'prerequisite',dungeons:['wailing-caverns'],pickup:place('Tonga Runetotem','The Crossroads'),chainUnresolved:false,objectives:'Begin the oasis investigation while leveling around the Crossroads.'},
    914:{prerequisites:[1490],chainUnresolved:false,turnIn:place('Nara Wildmane','Thunder Bluff')},
    6981:{starter:'item',turnIn:place(null,'Ratchet → above Wailing Caverns'),notes:['Complete the Naralex event after all Fang leaders. Keep the shard from Mutanus; follow the Ratchet directions before the final hand-in. Faction-specific follow-up mapping remains unresolved.']},
    1654:{requiredItems:[],chainUnresolved:true,notes:['Paladin: complete the Tome of Valor preparation before leaving Ironforge. Objectives span Deadmines, Shadowfang Keep and the Blackfathom approach plus the outdoor component. Do not mark objectives finished after just one dungeon.']},
    1740:{notes:['Warlock: accept from Doan Karhan in the Barrens before either SFK or BFD. Collect both sets of fragments across the two dungeons.']},
    2040:{chainUnresolved:true,notes:['Observed series has a prior stage. Confirm the Gnoarn → Shoni introduction before departure.']},
    166:{chainUnresolved:true,notes:['Complete the Defias investigation and escort before the VanCleef run. Published chain lengths differ between Classic and Forever; verify the active final stage.']},
    214:{chainUnresolved:true,notes:['Check Scout Riell after finishing the Defias investigation; a related quest link alone does not establish the unlock.']},
    373:{role:'followup',starter:'item',prerequisites:[],chainUnresolved:false,turnIn:place('Baros Alexston','Stormwind'),notes:['Loot the letter from VanCleef. Continue its Stormwind investigation before the Stockade; intermediate chain IDs need review.']},
    6561:{pickup:place("Argent Guard Thaelrid",'Blackfathom Deeps'),starter:'inside'},
    1198:{prerequisites:[],chainUnresolved:false},
    1200:{prerequisites:[1198],chainUnresolved:false,starter:'inside',pickup:place('Argent Guard Thaelrid','Blackfathom Deeps')},
    5127:{professions:['Blacksmithing'],chainUnresolved:true},
    2947:{role:'followup',prerequisites:[2945],chainUnresolved:false},
    2949:{role:'followup',prerequisites:[2945],chainUnresolved:false}
  };
  // A fixed itinerary with reviewable targets. Numbers are NOT quest-grey cutoffs.
  const plans = {
    'ragefire-chasm':{window:[14,16],region:'Durotar · capitals',hub:{Horde:'Razor Hill → Crossroads',Alliance:'No known Alliance quest package'},bind:{Horde:'Orgrimmar',Alliance:'Your current leveling hub'},circuit:['Thunder Bluff: Rahauro has both trogg/satchel pickups. Discover the flight path while there.','Undercity: collect The Power to Destroy before returning via the Orgrimmar zeppelin. Discover both city flight paths; do not assume they are already connected.','Orgrimmar: finish the Hidden Enemies preparation with Thrall and Neeru, and collect Slaying the Beast. Combine Skull Rock with Durotar leveling.'],inside:['Count the trogg kills before leaving their section. Visit Maur and accept the satchel follow-up.','Loot both books and the heart; defeat both Hidden Enemies targets, not just the final boss.'],after:['Finish the Thrall → Neeru → Thrall dialogue in Orgrimmar. Carry the satchel to Thunder Bluff and books to Undercity on the next capital circuit.'],travel:'Walk the Barrens/Mulgore route to Thunder Bluff; use discovered flights afterward. Zeppelin links Orgrimmar and Tirisfal. Bind Orgrimmar before the detour; hearth back only when available.',fallback:'If the hearthstone is cooling down, use the zeppelin/road return or do nearby hub quests first.',reserve:2,feasibility:'One clear is a candidate if the city preparation is complete and all required drops are obtained.'},
    'hall-of-thanes':{window:[16,18],region:'Dun Morogh · Ironforge',hub:{Alliance:'Kharanos → Gol’Bolar Quarry → Thelsamar',Horde:'Enemy-capital detour; eligibility unresolved'},bind:{Alliance:'Ironforge',Horde:'Your current leveling hub'},circuit:['Work the Dun Morogh quarry quests while looking for the Dark Iron Map. Complete Underground Map before requesting Old Ironforge Incursion.','In Old Ironforge, check Thom Filch and Afadra Dunwall. Do not delay the Deadmines preparation while hunting an uncertain drop.'],inside:['Speak to the Ghostly Attendant; check the Reliquary vault for the treaty. Complete required heirlooms, spirits and Durgen objectives.'],after:['Report Incursion to King Magni. Resolve the treaty hand-in before leaving the city.'],travel:'Discover Ironforge and Thelsamar flight paths. Use the Deeprun Tram for the Stormwind/Westfall circuit; no purchased portal is required.',fallback:'Use the tram or walk back through Dun Morogh if hearthstone is unavailable.',reserve:2,feasibility:'Treaty minimum is listed as 16. Earlier runs can require another visit. Horde availability and access are unresolved.'},
    'wailing-caverns':{window:[18,21],region:'Barrens · Thunder Bluff',hub:{Horde:'Crossroads → Ratchet',Alliance:'Westfall first; Ratchet detour for neutral quests'},bind:{Horde:'Crossroads',Alliance:'Ratchet'},circuit:['Ratchet: complete Raptor Horns for Mebok before Smart Drinks; collect Trouble at the Docks from Bigglefuzz on the same stop.','Horde: finish the oasis investigation with Tonga, then bundle the Hamuul/Nara chain and Zamah’s Serpentbloom pickup in one Thunder Bluff trip.','Visit Nalpak and Ebru above the cavern entrance before entering the instance.'],inside:['Find Mad Magglish in the outer cavern and finish required outdoor pickups before zoning in.','Finish Fang leaders and collection objectives before starting the Naralex event. Loot Mutanus for the shard.'],after:['Turn in at the cave and Ratchet, investigate the shard, then bundle the Thunder Bluff hand-ins.'],travel:'Unlock Crossroads, Ratchet and Thunder Bluff flights. Alliance: route via the Menethil–Theramore boat and roads to Ratchet; this is a substantial hostile-area detour, not a teleport.',fallback:'Walk back to the nearby hub; do nearby Barrens objectives while the hearthstone recovers.',reserve:2,feasibility:'One-clear candidate; shard/event drops and incomplete oasis-chain evidence prevent a guarantee.'},
    'deadmines':{window:[19,21],region:'Westfall · Stormwind',hub:{Alliance:'Sentinel Hill → Lakeshire',Horde:'Class/neutral eligibility unresolved'},bind:{Alliance:'Goldshire',Horde:'Your current leveling hub'},circuit:['Stormwind: bundle Wilder Thistlenettle and Shoni pickups before returning to Westfall. Check the Gnoarn introduction on the Ironforge trip.','Sentinel Hill: finish the Defias lead-in and escort; check Gryan and Scout Riell before entering Moonbrook.','Eligible non-Human characters: progress Alba’s Toxic Soil chain while doing wells, coastal murlocs, the mines and Moonbrook. Acquire the explosives before the run.','Paladin: wait until level 20 and obtain the Test of Righteousness before this run if eligible. Use the level 20 checkpoint to audit WC and Hall of Thanes rather than adding optional grinding.'],inside:['Clear the undead side area outside the instance for Wilder’s objectives.','Place Alba’s explosives in the forge when that quest is active; obtain the paladin component if applicable.','Loot VanCleef’s head and the Unsent Letter. Leave via the back exit for Alba; do not hearth straight from the ship.'],after:['Meet Alba outside, then turn in at Sentinel Hill and Stormwind. Start the Unsent Letter investigation for the Stockade on this visit.'],travel:'Unlock Stormwind, Sentinel Hill and Lakeshire flights. Combine the Ironforge preparation with the tram circuit.',fallback:'Exit normally for Alba, then use the Westfall road/flight return. Save the hearthstone for a later detour.',reserve:3,feasibility:'Paladin pickup at 20 and new Toxic Soil preparation can push the run later. Check the overlapping early dungeons before adding filler.'},
    'ruins-of-lordaeron':{window:[19,21],region:'Tirisfal · Silverpine',hub:{Horde:'Brill → Sepulcher',Alliance:'Southshore approach; hostile-area detour'},bind:{Horde:'Undercity',Alliance:'Southshore'},circuit:['Horde: collect Morbin’s limb quest and Theodore’s plague quest on one Undercity visit; inspect Brill for the Rath’mael lead.','Alliance: confirm Captain Truman’s pickup before traveling. Item-started insignia/letter quests cannot be assumed shareable.'],inside:['Keep every quest starter, including the head, insignias, letter and crest. Check faction-specific turn-ins before leaving.'],after:['Horde: bundle Undercity turn-ins. Alliance: bundle Stormwind recipients with the next city visit. The crest variants and later head chain still need ID verification.'],travel:'Combine with SFK preparation; do not use hostile Undercity as an Alliance transit hub.',fallback:'Use your faction’s road/flight route if hearthstone is unavailable.',reserve:5,feasibility:'Several new drop/follow-up records are unresolved. An all-quest one-clear claim is not yet possible.'},
    'shadowfang-keep':{window:[23,25],region:'Silverpine · Hillsbrad',hub:{Horde:'Sepulcher → Tarren Mill',Alliance:'Southshore'},bind:{Horde:'Sepulcher',Alliance:'Southshore'},circuit:['Horde: collect the Book of Ur in Undercity, then both Sepulcher quests before traveling south.','Warlock: obtain the Orb of Soran’ruk quest in the Barrens first; it also requires BFD. Paladin: obtain the Test of Righteousness first.'],inside:['Collect class components and the Book of Ur before moving on to Arugal.'],after:['Return through Sepulcher and Undercity; preserve cross-dungeon components until the complete class quest is ready.'],travel:'Unlock your faction’s Hillsbrad flight path and combine the trip with Ruins of Lordaeron.',fallback:'Return by road to your faction hub.',reserve:1,feasibility:'One-clear candidate for known pickups; class prerequisites remain provisional.'},
    'blackfathom-deeps':{window:[24,26],region:'Ashenvale',hub:{Horde:'Zoram’gar → Splintertree',Alliance:'Auberdine → Astranaar'},bind:{Horde:'Splintertree Post',Alliance:'Astranaar'},circuit:['Horde: collect Jeneu’s quests at Zoram’gar before entering. Alliance: bundle Darnassus and Auberdine pickups while traveling into Ashenvale.','Bring any active paladin/warlock quest from earlier stops; inspect the cave approach for outside objectives.'],inside:['Find Thaelrid and accept the inside quest before killing its target.','Collect crystals and the Fathom Core as applicable; handle Aquanis and Twilight objectives before the final section.'],after:['Return to the coastal hub, then combine capital hand-ins with training. Keep new Heart of the Void starters pending verification.'],travel:'Learn the coastal and Ashenvale hub flights; use the faction’s established boat/road connections.',fallback:'Return along the coast to the hub instead of waiting for hearthstone.',reserve:3,feasibility:'New Forever follow-ups and faction variants are unresolved; audit them before assuming one clear.'},
    'stockades':{window:[26,28],region:'Stormwind · Redridge · Wetlands',hub:{Alliance:'Lakeshire → Darkshire → Menethil',Horde:'No known Horde package'},bind:{Alliance:'Stormwind',Horde:'Your current leveling hub'},circuit:['Advance the Unsent Letter investigation before accepting the Stockade Riots stage.','Bundle Redridge and Duskwood pickups while leveling there. Pick up The Fury Runs Deep through the Wetlands Dark Iron chain on the Menethil journey.'],inside:['Confirm all named targets and prisoner counts before leaving each cell block.'],after:['Turn in Stormwind stages immediately, then return the regional pickups on the Wetlands/Redridge route.'],travel:'Discover Lakeshire, Darkshire, Menethil and Thelsamar; use flights only after discovery.',fallback:'Stay in Stormwind for local hand-ins; use roads for missing flight links.',reserve:1,feasibility:'A single clear requires geographically scattered pickups first; the Unsent Letter chain is not optional.'},
    'excavation-site':{window:[27,29],region:'Wetlands',hub:{Alliance:'Menethil → Whelgar’s excavation',Horde:'Arathi approach; verify access'},bind:{Alliance:'Menethil',Horde:'Tarren Mill'},circuit:['Combine the Wetlands survey, delivery and raptor prerequisites before entering. Follow the linked chain checklist; several newly added stages have uncertain ordering.'],inside:['Check quest items, escort availability and all inside starters before the final boss.'],after:['Return through the Wetlands quest hubs; do not vendor newly found starter items.'],travel:'Use the existing Menethil/Thelsamar connection on Alliance; Horde uses its Hillsbrad/Arathi roads, not Alliance flights.',fallback:'Quest nearby while waiting for the return cooldown.',reserve:4,feasibility:'New dungeon: exact pickup and prerequisite routing remains incomplete.'},
    'gnomeregan':{window:[30,33],region:'Dun Morogh · capitals',hub:{Alliance:'Ironforge → Wetlands',Horde:'Orgrimmar → Ratchet'},bind:{Alliance:'Ironforge',Horde:'Ratchet'},circuit:['Bundle Tinker Town quests. Horde: complete the Rig Wars/Chief Engineer Scooty access preparation before leaving Ratchet.','Check the essential artificials, data card and radioactive collection quests together; reserve slots for inside quests.'],inside:['Follow data-card upgrades in order. Complete the rescue before abandoning the clean zone.','Do not leave before inspecting the grime-encrusted ring and the Sparklematic.'],after:['Some outside hand-ins unlock a second collection stage. The Only Cure is More Green Glow can require returning to still uncleared radioactive enemies.'],travel:'Alliance can walk from Ironforge; Horde access item/teleporter route must be confirmed, with the long overland route as fallback.',fallback:'Do local Dun Morogh or Ratchet work instead of assuming a free hearth return.',reserve:4,feasibility:'Potential same-instance return after an outside hand-in; a reset may be needed if required enemies are gone.',revisit:'outside-return'},
    'razorfen-kraul':{window:[31,34],region:'Southern Barrens · Thousand Needles',hub:{Horde:'Camp Taurajo → Freewind Post',Alliance:'Theramore → Thalanaar'},bind:{Horde:'Camp Taurajo',Alliance:'Theramore'},circuit:['Collect capital quests before going south. Inspect Lonebrow’s Journal/Crone preparation on the Thousand Needles circuit.','Preserve tools supplied for Blueleaf Tubers and accept class quests before the run.'],inside:['Do tubers and other side objectives before starting an escort. Inspect the scroll that begins An Unholy Alliance.'],after:['Turn in the scroll before the Razorfen Downs trip. Class and Elemental Aid follow-ups still need beta verification.'],travel:'Combine southern Barrens and Thousand Needles travel; discover the faction hub flight points.',fallback:'Return by the same roads and use nearby leveling quests.',reserve:3,feasibility:'One-clear candidate, subject to escort success and new quest audit.'},
    'city-of-dalaran':{window:[30,33],region:'Alterac · Hillsbrad',hub:{Alliance:'Southshore',Horde:'Tarren Mill'},bind:{Alliance:'Southshore',Horde:'Tarren Mill'},circuit:['Inspect faction-friendly Alterac/Hillsbrad quest hubs before entering. Eight observed quest titles are not yet mapped to complete pickup records.'],inside:['Hold this chapter until the quest IDs, starters and chains can be checked.'],after:['Keep any new quest items; turn-in routing is unverified.'],travel:'Use your faction’s Hillsbrad road and flight network.',fallback:'Continue nearby outdoor quests without assuming the dungeon package is complete.',reserve:4,feasibility:'Unresolved inventory: do not use this chapter as a ready checklist.'},
    'scarlet-monastery':{window:[34,38],region:'Tirisfal · Hillsbrad · Desolace',hub:{Alliance:'Southshore → Desolace circuit',Horde:'Tarren Mill → Undercity'},bind:{Alliance:'Southshore',Horde:'Undercity'},circuit:['Alliance: complete Brother Anton’s Desolace chain before requesting In the Name of the Light from Raleigh in Southshore.','Horde: bundle Undercity/Thunder Bluff pickups and the Test of Lore chain. Undead characters have a documented Compendium of the Fallen restriction.','Mage: obtain Rituals of Power before Library. Graveyard/Library objectives can be earlier than Armory/Cathedral; inspect their minimums separately.'],inside:['Graveyard: inspect Vorrel’s quest. Library: collect books and the Scarlet Key.','Use the key for Armory/Cathedral where required. Finish multi-wing kill quests only after all their targets.'],after:['Return Vorrel’s external objective separately. Bundle Southshore/Undercity hand-ins before resuming leveling.'],travel:'Learn Hillsbrad connections during SFK preparation; the Alliance Desolace prerequisite is a mandatory detour if that quest is included.',fallback:'Use faction-safe roads; do not assume enemy-city flights.',reserve:2,feasibility:'Four separate wings, not one instance clear. Early book/Graveyard quests must be reviewed before delaying all wings to Cathedral level.',visits:['Graveyard · early objectives','Library · books + key','Armory · kill objectives','Cathedral · final kill objectives']},
    'razorfen-downs':{window:[39,42],region:'Southern Barrens',hub:{Horde:'Freewind Post → Camp Taurajo',Alliance:'Theramore → Dustwallow'},bind:{Horde:'Camp Taurajo',Alliance:'Theramore'},circuit:['Complete the RFK scroll chain before taking its Downs follow-up. Collect capital pickups before the southern trip.'],inside:['Check Belnistrasz’s prerequisite dialogue before beginning the idol escort; leave it until the party can commit.'],after:['Turn in nearby/capital quests on the return trip.'],travel:'Reuse southern Barrens flight paths from RFK.',fallback:'Use the road to the same faction hub.',reserve:2,feasibility:'One-clear candidate, but escort failure can force a repeat; source level ranges disagree.'},
    'uldaman':{window:[42,45],region:'Badlands · Loch Modan',hub:{Alliance:'Thelsamar → Badlands',Horde:'Kargath'},bind:{Alliance:'Thelsamar',Horde:'Kargath'},circuit:['Bundle Badlands reagents and lost-dwarf/tablet chains with outdoor Badlands leveling.','Keep the staff pieces used for chamber access; confirm which steps require an outside hand-in.'],inside:['Check the outer dig for quest starts before the deeper instance. Complete tablet/reagent objectives before committing to the final chamber.'],after:['The Platinum Discs dialogue and outside follow-ups are separate steps. Check for a return requirement before resetting.'],travel:'Discover Kargath or Thelsamar as appropriate; no enemy-faction flight access.',fallback:'Return through Badlands/Loch Modan roads.',reserve:3,feasibility:'Outer area and deep dungeon are different objectives; follow-up prerequisites remain provisional.'},
    'zul-farrak':{window:[44,47],region:'Tanaris · Hinterlands',hub:{Alliance:'Gadgetzan',Horde:'Gadgetzan'},bind:{Alliance:'Gadgetzan',Horde:'Gadgetzan'},circuit:['Bundle Gadgetzan pickups. Finish the Hinterlands medallion preparation and Spider God chain before traveling to Tanaris.','Complete Screecher Spirits with Yeh’kinya before taking the tablets quest. Verify the current Gahz’rilla summoning requirement; do not assume another player brought it.'],inside:['Resolve the pyramid event before Bly’s confrontation. Collect medallion/tablets and check all side bosses needed by active quests.'],after:['Return to Gadgetzan and Steamwheedle; continue Yeh’kinya’s chain for Sunken Temple.'],travel:'Use established Tanaris flight paths; batch the Hinterlands detour with other Eastern Kingdoms work.',fallback:'Walk between Gadgetzan and Steamwheedle; use local quests while cooldown recovers.',reserve:2,feasibility:'One-clear candidate only with the cross-continent prerequisites and summoning access ready.'},
    'maraudon':{window:[46,49],region:'Desolace · Feralas',hub:{Alliance:'Nijel’s Point → Feathermoon',Horde:'Shadowprey → Camp Mojache'},bind:{Alliance:'Nijel’s Point',Horde:'Shadowprey Village'},circuit:['Combine Desolace pickups before either entrance. Verify the Scepter of Celebras quest and inventory space for both components.'],inside:['Use a full orange + purple + inner route if collecting every objective. Complete the Celebras interaction before leaving.'],after:['Turn in at the faction Desolace hub, then continue toward Feralas.'],travel:'Discover both Desolace and Feralas hub connections on the overland journey.',fallback:'Return by road to the Desolace hub.',reserve:2,feasibility:'Three connected sections; a princess-only run is not full quest coverage.',visits:['Orange entrance objectives','Purple entrance objectives','Inner section + Princess']},
    'sunken-temple':{window:[51,54],region:'Swamp of Sorrows · Tanaris · Un’Goro',hub:{Alliance:'Nethergarde → Swamp approach',Horde:'Stonard'},bind:{Alliance:'Nethergarde',Horde:'Stonard'},circuit:['Complete the ZF/Yeh’kinya chain before The God Hakkar. Bundle Tanaris and Un’Goro prerequisites on the way east.','Check every class quest with your trainer; faction and profession steps must be verified before departure.'],inside:['Bring the Hakkar summoning item and follow the event objectives in order. Complete upper and lower section quests before leaving.'],after:['Batch Swamp, Tanaris and Un’Goro turn-ins; keep next-stage items.'],travel:'Use your faction hub in the southeast; avoid routing Alliance through Stonard services.',fallback:'Use the safe road return to your own hub.',reserve:3,feasibility:'Class and summoning chains can require more preparation than the minimum entry level suggests.'},
    'blackrock-depths':{window:[54,58],region:'Searing Gorge · Burning Steppes',hub:{Alliance:'Thorium Point → Morgan’s Vigil',Horde:'Thorium Point → Flame Crest'},bind:{Alliance:'Morgan’s Vigil',Horde:'Kargath'},circuit:['Bundle Gorge/Steppes pickups. Accept Attunement to the Core at level 55 before the deep run.','Prepare required Love Potion materials and supplied quest items before the bar section. Dark Iron Legacy has a spirit-only pickup: this route does not schedule a death skip; its access remains an explicit exception.'],inside:['First visit: prison/early chain objectives and key preparation where available.','Return visit: complete newly unlocked objectives, then bar, forge and deep-route/attunement targets. Do not reset before checking chain hand-ins.'],after:['Windsor, Kharan and Gor’shak chains can require outside dialogue and a return. Preserve unfinished stages rather than marking a full clear complete.'],travel:'Learn Thorium Point and the faction Steppes hub; cluster Blackrock trips with LBRS/UBRS preparation.',fallback:'Use those flight paths and roads rather than an assumed portal.',reserve:5,feasibility:'One-clear coverage is not demonstrated: prison/outside/deeper follow-ups conflict.',revisit:'outside-return',visits:['Prison + chain setup','Outside hand-ins','Return for unlocked objectives + deep route']},
    'dire-maul':{window:[56,60],region:'Feralas',hub:{Alliance:'Feathermoon',Horde:'Camp Mojache'},bind:{Alliance:'Feathermoon',Horde:'Camp Mojache'},circuit:['Prepare Felvine and Elven Legends prerequisites. Inspect class books, librams and profession requirements separately.'],inside:['East: key and Felvine objectives. West/North: confirm key access and which objectives conflict with a tribute route.'],after:['Library hand-ins can be separate from combat clears; count repeatables once per compatible character.'],travel:'Use the Feralas hub from the Maraudon circuit.',fallback:'Return by road; use Feralas quests for any level deficit.',reserve:4,feasibility:'Separate wings. Tribute versus kill choices need explicit branch verification; full coverage is unresolved.',visits:['East','West','North / tribute conflict review']},
    'lower-blackrock-spire-lbrs':{window:[58,60],region:'Blackrock · capitals',hub:{Alliance:'Morgan’s Vigil',Horde:'Kargath'},bind:{Alliance:'Morgan’s Vigil',Horde:'Kargath'},circuit:['Bundle faction orders, tablets and Bijou preparation before entry. Check UBRS access requirements at the same time.'],inside:['Visit Bijou before progressing beyond her belongings route. Keep key/gem drops and quest starters.'],after:['Advance the faction attunement chain before scheduling UBRS.'],travel:'Reuse the Blackrock flight network.',fallback:'Return through Burning Steppes/Searing Gorge.',reserve:4,feasibility:'Key drops and attunement chains may require repeated cleared content; do not guarantee a single reset.',revisit:'possible-reset'},
    'upper-blackrock-spire-ubrs':{window:[60,60],region:'Blackrock · attunement circuits',hub:{Alliance:'Stormwind → Morgan’s Vigil',Horde:'Orgrimmar → Kargath'},bind:{Alliance:'Morgan’s Vigil',Horde:'Kargath'},circuit:['Finish the LBRS/faction attunement steps and verify Seal of Ascension access.','Blacksmiths: resolve The Demon Forge requirements. Prepare egg-collection tools before entry.'],inside:['Complete Emberseer, egg and Drakkisath objectives in route order; keep the required champion blood.'],after:['Finish the Drakefire Amulet/Onyxia chain outside the dungeon; level 60 does not end this itinerary.'],travel:'Batch capital and remote dragon-chain visits before the final UBRS objectives.',fallback:'Use established flights; no summoned access is assumed.',reserve:3,feasibility:'Attunement and key chains are provisional; multiple visits may be unavoidable.',revisit:'possible-reset'},
    'scholomance':{window:[58,60],region:'Western Plaguelands',hub:{Alliance:'Chillwind Camp',Horde:'The Bulwark'},bind:{Alliance:'Chillwind region',Horde:'Undercity'},circuit:['Complete the key preparation or independently verify another legitimate access method. Bundle Caer Darrow chains before entry.'],inside:['Check Kirtonos and Krastinov sequencing before clearing their targets. Paladins must prepare their class event separately.'],after:['Several Caer Darrow stages send you back after a hand-in. Keep the current instance if usable; a fresh target may require a reset.'],travel:'Discover the faction Plaguelands hub and Light’s Hope.',fallback:'Use the road to the faction hub; do not assume the suggested hub has an inn.',reserve:4,feasibility:'Chained boss objectives require explicit return planning.',revisit:'possible-reset'},
    'stratholme':{window:[58,60],region:'Eastern Plaguelands',hub:{Alliance:'Light’s Hope → Chillwind',Horde:'Light’s Hope → Bulwark'},bind:{Alliance:'Your nearest confirmed inn',Horde:'Undercity'},circuit:['Finish Tirion’s outdoor chain before Of Love and Family. Bundle Light’s Hope and faction-camp pickups.','Review class and armor-upgrade chains separately; their availability in Forever is not confirmed.'],inside:['Living side: painting and Scarlet objectives. Undead side: plague samples and boss objectives.','Inspect Aurius/medallion ordering and newly unlocked quests before the Baron event.'],after:['Turn in samples before any Active Agent return. Preserve the instance when possible; a repeat objective can require a new clear.'],travel:'Combine Eastern/Western Plaguelands routes; use discovered flights.',fallback:'Road back to the nearest safe hub.',reserve:4,feasibility:'Living and undead sections plus staged follow-ups are not one guaranteed clear.',revisit:'possible-reset',visits:['Living side','Undead side','Follow-up return if required']}
  };
  const newPlans = [
    ['the-drowned-city',[36,39],'Stranglethorn','Booty Bay'],['kroldok-stronghold',[41,44],'Riverglades','Your confirmed Riverglades hub'],['alcaz-prison',[49,52],'Dustwallow Marsh','Your faction’s Dustwallow hub'],['timbermaw-hold',[56,59],'Felwood','Your faction’s Felwood hub'],['shapers-terrace',[59,60],'Un’Goro Crater','Marshal’s Refuge']
  ];
  plans['scarlet-monastery'].wingPlans=[
    {id:'graveyard',name:'Graveyard',window:[28,31],questIds:[1051],reason:'Horde: obtain Vorrel’s inside quest, then complete its outdoor return. Do not wait for Cathedral solely to start this stage.'},
    {id:'library',name:'Library',window:[34,36],questIds:[1048,1053,1049,1050,1160,1951],reason:'The multi-wing kill quests unlock later than the book pickups. Prepare the faction chain first if aiming for one Library clear.'},
    {id:'armory',name:'Armory',window:[36,38],questIds:[1048,1053],reason:'Bring the key from Library and the active multi-wing kill quest.'},
    {id:'cathedral',name:'Cathedral',window:[38,40],questIds:[1048,1053],reason:'Finish the multi-wing targets, then turn in. These are provisional planning targets, not non-grey guarantees.'}
  ];
  plans['scarlet-monastery'].window=[28,40];
  plans['ragefire-chasm'].flights=['Orgrimmar','Thunder Bluff'];
  plans['wailing-caverns'].flights=['Ratchet','Thunder Bluff'];
  plans['deadmines'].flights=['Stormwind','Sentinel Hill'];
  plans['hall-of-thanes'].flights=['Ironforge','Thelsamar'];
  plans['ragefire-chasm'].circuit[0]+=' At level 14+, also check Zamah’s Serpentbloom pickup for Wailing Caverns; combine it with this visit.';
  for(const [id,window,region,hub] of newPlans)plans[id]={window,region,hub:{Alliance:hub,Horde:hub},bind:{Alliance:'Your nearest confirmed inn',Horde:'Your nearest confirmed inn'},circuit:['Quest inventory, entry requirements and prerequisites are not verified. Inspect local quest hubs before committing to a clear.'],inside:['Unresolved: no complete objective checklist is available.'],after:['Keep new starters and record their turn-ins; no automatic completion credit.'],travel:'Connection and pickup routing need beta confirmation.',fallback:'Continue regional outdoor leveling without treating this dungeon as covered.',reserve:3,feasibility:'Unverified new dungeon; no one-clear claim.'};
  const starters = {
    Horde:{title:'Starting lands → the first capital circuit',window:[1,13],hub:'Your racial starting zone → Durotar / Barrens',steps:['Finish the local opening and class-training quests. Move toward Razor Hill/Crossroads by the first dungeon checkpoint, not by an assumed XP total.','Tauren: collect Thunder Bluff pickups before leaving Mulgore. Undead: collect Undercity pickups before taking the zeppelin. Orc/Troll: batch both capital detours after discovering Orgrimmar.','Skyborne starting connections are unverified; use the normal faction travel network once available. Do not assume a portal or summon.','Bind in a confirmed inn near current leveling. Discover each flight master in person. Before the capital circuit, reserve space for the RFC quests and inside follow-up.']},
    Alliance:{title:'Starting lands → Ironforge and Westfall',window:[1,15],hub:'Your racial starting zone → Dun Morogh / Westfall',steps:['Finish the local opening and class-training quests. Human: work Westfall preparation while planning the Ironforge detour. Dwarf/Gnome: bundle the quarry/map chain before taking the tram to Stormwind.','Night Elf: prepare Darkshore pickups before the boat journey through Menethil. Travel inland through Wetlands carefully; no death skip or purchased teleport is assumed.','Skyborne starting connections are unverified. Join the Ironforge/Stormwind circuit through your unlocked faction transport.','Discover Ironforge, Stormwind and Sentinel Hill flights. Review Hall of Thanes at level 16 and Deadmines around 19–21; avoid optional grinding if either package is ready.']}
  };
  function catalog(raw) {
    const data=JSON.parse(JSON.stringify(raw));
    data.routeVersion=version;
    for(const q of additions){const base={minLevel:null,questLevel:null,classMask:0,raceMask:'0',professions:[],pickup:null,turnIn:null,prerequisites:[],relatedQuestIds:[],chainUnresolved:false,sharing:'unknown',sharingConfidence:'unknown',starter:'npc',requiredItems:[],itemRefs:[],repeatable:null,branch:null,confidence:'provisional',sources:[source(q.id)],notes:[],objectives:null};data.quests.push({...base,...q});}
    for(const q of data.quests){if(corrections[q.id]){Object.assign(q,corrections[q.id]);q.sources.push(source(q.id));}q.revision=version;q.role ||= 'dungeon';}
    // A related ID without verified direction remains a blocker, not an invented edge.
    for(const q of data.quests)for(const id of q.relatedQuestIds){const linked=data.quests.find(x=>x.id===id);if(linked&&!linked.dungeons.length){linked.dungeons=[...q.dungeons];linked.role='chain-unresolved';}}
    for(const d of data.dungeons){d.questIds=data.quests.filter(q=>q.dungeons.includes(d.id)).map(q=>q.id);d.observedGaps=(d.observedGaps||[]).filter(g=>!data.quests.some(q=>q.dungeons.includes(d.id)&&q.name===g.name&&q.observed));d.plan=plans[d.id];}
    data.observedGaps=data.dungeons.flatMap(d=>d.observedGaps);
    return data;
  }
  const api={version,plans,starters,additions,corrections,catalog,stepId};
  if(typeof module==='object'&&module.exports)module.exports=api;else root.ForeverLevelingRoutes=api;
})(globalThis);
