(function() {
  'use strict';
  const E=window.ForeverLeveling,R=window.ForeverLevelingRoutes,D=R.catalog(window.ForeverLevelingData),KEY='forever-toolkit-leveling-v1';
  const $=id=>document.getElementById(id);
  const el=(tag,text,attrs={})=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;};
  const option=(value,label)=>el('option',label,{value});
  const current=()=>library.characters.find(c=>c.id===library.activeId);
  let library={schemaVersion:1,activeId:null,characters:[]},chapterId='start',creating=false,storageBlocked=false,coverageFilter='all';
  const say=(text,error=false)=>{$('message').textContent=text;$('message').hidden=!text;$('message').setAttribute('role',error?'alert':'status');};
  try{const saved=localStorage.getItem(KEY);if(saved)library=E.importLibrary(saved);}catch(error){storageBlocked=true;say('Browser progress could not be read. The original storage has been left untouched; export this session to keep new progress.',true);}
  function uniqueName(base){let n=base,i=2;while(library.characters.some(c=>c.name.toLowerCase()===n.toLowerCase()))n=base.slice(0,64)+` (${i++})`;return n;}
  if(!library.characters.length){const c=E.character('character-'+Date.now(),'My character',{},D.dataVersion,D.routeVersion);library.characters.push(c);library.activeId=c.id;}
  try{const shared=E.readRouteParams(location.search,D);if(shared){let hash=0;for(const ch of E.routeParams(shared.selection,shared.chapter))hash=(Math.imul(hash,31)+ch.charCodeAt(0))|0;const id='shared-'+(hash>>>0);let c=library.characters.find(c=>c.id===id);if(!c){c=E.character(id,uniqueName('Shared route'),shared.selection,D.dataVersion,D.routeVersion);library.characters.push(c);}library.activeId=id;chapterId=shared.chapter||'start';say('Shared route opened as a separate character. Private progress was not included in the link.');}}catch(e){say(e.message,true);}
  function save(){if(storageBlocked)return;try{localStorage.setItem(KEY,JSON.stringify(library));}catch(e){say('Not saved to browser. Your checklists still work in this tab; export progress before closing it.',true);}}
  function update(fn){try{const active=document.activeElement?.id;const next=fn(JSON.parse(JSON.stringify(current())));if(next)library.characters[library.characters.findIndex(c=>c.id===library.activeId)]=E.validateCharacter(next);save();render();if(active)$(active)?.focus({preventScroll:true});}catch(error){say(error.message,true);}}
  const btn=(text,fn,attrs={})=>{const b=el('button',text,{type:'button',...attrs});b.addEventListener('click',fn);return b;};
  function details(title,key){const d=el('details',null,{'data-key':key});d.append(el('summary',title));return d;}
  const badge=status=>el('span',status,{class:'badge '+(status==='Ready'?'ready':status==='Level risk'?'risk':status==='Preparation needed'?'preparation':'')});
  function labeled(label,input){const l=el('label',label);l.append(input);return l;}
  function selectControl(values,value,onchange,id){const s=el('select',null,id?{id}:{});values.forEach(v=>s.append(option(Array.isArray(v)?v[0]:v,Array.isArray(v)?v[1]:v)));s.value=value;s.addEventListener('change',()=>onchange(s.value));return s;}
  function inputControl(type,value,onchange,attrs={}){const i=el('input',null,{type,...attrs});i.value=value;i.addEventListener('change',()=>onchange(i.value));return i;}
  function stepList(parent,texts,prefix){const list=el('ol',null,{class:'check-steps'});texts.forEach((text,index)=>{const id=R.stepId(prefix,text),li=el('li'),check=el('input',null,{type:'checkbox',id:'step-'+id});check.checked=current().steps[id]?.done===true;check.addEventListener('change',()=>update(c=>{c.steps[id]={done:check.checked,revision:D.routeVersion};return c;}));const l=el('label',null,{class:check.checked?'done':''});l.append(check,el('span',text));li.append(l);const old=current().steps[id];if(old&&old.revision!==D.routeVersion)li.append(el('small','Instruction changed—review this checked step.'));list.append(li);});parent.append(list);}
  function showChapter(id){chapterId=id;render();$('chapter').scrollIntoView({behavior:'instant',block:'start'});}
  function renderMobileChapters(){const s=$('mobile-chapter');s.replaceChildren(option('start','Starting route'),...E.itinerary(current(),D).map(r=>option(r.d.id,r.d.plan.window.join('–')+' · '+r.d.name)));s.value=chapterId;}
  function renderOverview(){const c=current(),cov=E.coverage(c,D),rows=E.itinerary(c,D),next=rows.find(r=>!r.complete&&r.quests.some(q=>E.eligibility(q,c).state==='eligible'));$('overview').replaceChildren();for(const [value,label]of [[cov.counts.completed,'turned in'],[cov.counts.routed,'routed'],[cov.counts.unresolved,'need review']]){const v=el('div');v.append(el('strong',value),el('span',' '+label));$('overview').append(v);}const n=el('div',null,{class:'next'});n.append(el('span','Next dungeon · '),btn(next?.d.name||'Review remaining coverage',()=>next?showChapter(next.d.id):$('coverage').open=true));$('overview').append(n);}
  function renderChapters(){const c=current(),search=$('chapter-filter').value.toLowerCase();$('chapters').replaceChildren();if(!search){const b=btn(`1–${R.starters[c.selection.faction].window[1]} · Starting route`,()=>showChapter('start'));if(chapterId==='start')b.setAttribute('aria-current','step');$('chapters').append(b);}const rows=E.itinerary(c,D).filter(r=>(r.d.name+' '+r.d.plan.region).toLowerCase().includes(search));for(const row of rows){const b=btn('',()=>showChapter(row.d.id));b.append(el('small',`${row.d.plan.window.join('–')} · ${row.d.plan.region}`),el('span',row.d.name,{class:'chapter-name'}),el('small',row.complete?'Mapped hand-ins recorded':row.status));if(chapterId===row.d.id)b.setAttribute('aria-current','step');$('chapters').append(b);}if(!rows.length)$('chapters').append(el('p','No matching dungeon.'));}
  function place(p){if(!p)return 'Unresolved';return [p.npc,p.zone,p.coordinates?`(${p.coordinates.join(', ')}) · ${p.confidence} coordinates`:null].filter(Boolean).join(' · ')||'Unresolved';}
  function questRow(q){const c=current(),row=el('div',null,{class:'quest-row'}),info=el('div'),e=E.eligibility(q,c),req=E.requirements(q,c,D);info.append(el('h4',q.name),el('small',`#${q.id} · pickup ${q.minLevel??'?'} · quest level ${q.questLevel??'?'} · ${q.role.replaceAll('-',' ')} · ${q.observed?'observed record / provisional route':q.confidence}`));const detail=details('Pickup, chain & requirements','quest-'+q.id);detail.className='quest-facts';detail.append(el('p','Pick up: '+place(q.pickup)),el('p','Objective: '+(q.objectives||'Not yet verified. Check the live quest text; do not treat a boss kill as automatic completion.')),el('p','Turn in: '+place(q.turnIn)));
    if(q.prerequisites.length)detail.append(el('p','First turn in: '+q.prerequisites.map(id=>`${D.quests.find(q=>q.id===id)?.name||'Quest'} #${id}`).join(' → ')));
    if(q.relatedQuestIds.length)detail.append(el('p','Related records (not necessarily prerequisites): '+q.relatedQuestIds.map(id=>`${D.quests.find(q=>q.id===id)?.name||'Quest'} #${id}`).join(', ')));
    if(q.chainUnresolved)detail.append(el('p','Unresolved chain: the complete sequence is not yet verified.'));
    if(q.branch){const values=[...new Set(D.quests.filter(x=>x.branch?.group===q.branch.group).map(x=>x.branch.value))];detail.append(labeled('Quest branch',selectControl([['','Not chosen'],...values],c.branches[q.branch.group]||'',v=>update(c=>{if(v)c.branches[q.branch.group]=v;else delete c.branches[q.branch.group];return c;}))));}
    detail.append(el('p',q.repeatable===true?'Repeatable: counted once in this guide.':q.repeatable===false?'One-time quest.':'Repeatability not verified; progress counts this ID once.'));
    if(q.itemRefs?.length)detail.append(el('p','Referenced items (not an inferred carry requirement): '+q.itemRefs.map(i=>`${i.name} #${i.id}`).join(', ')));
    if(q.requiredItems.length){const inv=el('div',null,{class:'inventory-list'});for(const item of q.requiredItems){const check=el('input',null,{type:'checkbox'});check.checked=!!c.inventory[item];check.addEventListener('change',()=>update(c=>{c.inventory[item]=check.checked;return c;}));const l=el('label');l.append(check,el('span','Carrying '+item));inv.append(l);}detail.append(inv);}
    if(req.missing.length)detail.append(el('p',req.missing.join(' ')));
    if(e.state==='unknown')detail.append(el('p',e.reason));
    q.notes.forEach(n=>detail.append(el('p',n)));
    if(q.dungeons.length>1)detail.append(el('p','Cross-dungeon quest: '+q.dungeons.map(id=>D.dungeons.find(d=>d.id===id)?.name||id).join(' + ')+'. Keep all components; only mark objectives complete when the entire quest is finished.'));
    detail.append(el('p',`Sharing: ${q.sharing} · ${q.sharingConfidence}. Default: collect it yourself.`));const share=E.canReceiveShare(q,c,D),shareButton=btn('I received this verified shared quest',()=>update(c=>E.setQuest(c,q,'accepted',D,true)));shareButton.disabled=!share.allowed;shareButton.title=share.reasons.join(' ');detail.append(shareButton);
    const evidence=el('p');for(const [index,s]of [...new Set(q.sources)].entries()){const entry=D.sources[s]||{url:s,title:'Individual Forever quest record'};if(!/^https:\/\//.test(entry.url))continue;const a=el('a',entry.title,{href:entry.url,target:'_blank',rel:'noopener'});if(index)evidence.append(document.createTextNode(' · '));evidence.append(a);}detail.append(evidence);info.append(detail);
    const control=el('div',null,{class:'quest-control'});control.append(labeled('Your quest progress',selectControl([['none','Not accepted'],['accepted','Accepted'],['objectives','Objectives complete'],['turned-in','Turned in'],['skipped','Skipped—not complete']],E.stage(c,q.id),v=>update(c=>E.setQuest(c,q,v,D)),`quest-${q.id}`)));if(c.quests[q.id]&&c.quests[q.id].revision!==q.revision)control.append(el('small','Record changed; review details.'));row.append(info,control);return row;
  }
  function renderTravel(parent,d){const c=current(),p=d.plan,t=E.travel(c,p),box=details('Travel, hearthstone & quest-log space','travel-'+d.id);box.append(el('p',p.travel),el('p',`Suggested bind: ${t.bind}. Confirm an inn before changing your bind.`),el('p',t.reason+' '+t.fallback));const controls=el('div',null,{class:'compact-controls'});controls.append(labeled('Actual hearthstone bind',inputControl('text',c.hearth.bind,v=>update(c=>{c.hearth.bind=v.slice(0,100);return c;}),{id:'hearth-bind',maxlength:100})),btn('Record hearth use',()=>update(c=>E.useHearth(c,D))),btn('Mark hearth ready',()=>update(c=>{c.hearth.readyAt=0;return c;})));box.append(controls);
    const capacity=el('div',null,{class:'compact-controls'});capacity.append(labeled('Other active quests',inputControl('number',c.otherQuestSlots,v=>update(c=>{const n=Number(v);if(!Number.isInteger(n)||n<0||n>100)throw Error('Use 0–100 other quests.');c.otherQuestSlots=n;return c;}),{min:0,max:100,id:'other-quests'})),labeled('Your quest-log limit',inputControl('number',c.logCapacity,v=>update(c=>{const n=Number(v);if(!Number.isInteger(n)||n<1||n>100)throw Error('Use a quest-log limit from 1–100.');c.logCapacity=n;return c;}),{min:1,max:100,id:'log-limit'})));box.append(capacity,el('p',`${E.logUse(c)} occupied · reserve ${p.reserve} for inside pickups. The initial 20-slot limit is a Classic fallback; enter your actual beta limit.`));
    box.append(labeled('Discovered flight paths (comma separated)',inputControl('text',c.flightPaths.join(', '),v=>update(c=>{c.flightPaths=[...new Set(v.split(',').map(s=>s.trim()).filter(Boolean))].slice(0,200);return c;}),{id:'flight-paths'})),el('p','Only use a flight when both endpoints are discovered. Missing connections require the described road/boat route. Flight availability and travel durations are not simulated.'));if(p.flights){const missing=p.flights.filter(x=>!c.flightPaths.includes(x));box.append(el('p',missing.length?'Not recorded as discovered: '+missing.join(', ')+'. Take the road/boat fallback until both endpoints are learned.':'Suggested flight endpoints are recorded; confirm the actual connection in-game.'));}parent.append(box);
  }
  function renderChapter(){const c=current(),host=$('chapter');host.replaceChildren();if(chapterId==='start'){const s=R.starters[c.selection.faction];host.append(el('h2',s.title),el('p',`${s.window.join('–')} · ${s.hub}`,{class:'muted'}));stepList(host,s.steps,c.selection.faction.toLowerCase()+'-start');host.append(el('h3','At each level checkpoint'),el('p','Update your level after a dungeon and again before major turn-in circuits. If ahead, remove optional outdoor quests before postponing an unfinished dungeon. If behind, stay in the nearby hub rather than repeating a cleared dungeon.'),el('p','All numbered windows are planning targets. Verified Forever grey thresholds are unavailable; inspect quest colour at hand-in. Green is acceptable.'));const next=E.itinerary(c,D).find(r=>!r.complete&&r.quests.some(q=>E.eligibility(q,c).state==='eligible'));if(next)host.append(btn('Prepare '+next.d.name,()=>showChapter(next.d.id)));return;}
    const d=D.dungeons.find(d=>d.id===chapterId);if(!d){chapterId='start';renderChapter();return;}const r=E.readiness(d,c,D),p=d.plan,w=r.window;
    const title=el('div',null,{class:'chapter-title'}),t=el('div');t.append(el('h2',d.name),el('p',`${p.window.join('–')} · ${p.region}`));title.append(t,badge(r.status));host.append(title,el('p',r.reason,{class:'chapter-status'}));
    const facts=el('dl',null,{class:'level-facts'});for(const [label,value]of [['Planned run',p.window.join('–')],['Entry minimum',d.entryLevel==null?'Unverified':`${d.entryLevel} · provisional`],['Highest known pickup',w.earliestKnownPickup+(w.unknownPreparation?' + unresolved chain':'')],['Non-grey deadline',w.lastNonGrey??'Unverified']]){const div=el('div');div.append(el('dt',label),el('dd',value));facts.append(div);}host.append(facts);
    const levels=details('Level checkpoints & overlapping dungeons','windows-'+d.id);levels.append(el('p',`Group range in the roster: ${d.groupRange?.join('–')||'unverified'}. This is not an entry limit or a quest-grey deadline. Allow for levels gained inside and before hand-ins.`));const turnin=inputControl('number',c.selection.level,v=>{const n=Number(v);if(!Number.isInteger(n)||n<c.selection.level||n>60){say('Hand-in level must be between your current level and 60.',true);return;}const x=E.windows(d,c,D,n);$('turnin-risk').textContent=x.turnInRisk?'This hand-in level exceeds a verified non-grey deadline.':x.unknownGrey?'Grey threshold unverified: check quest colours at this level.':'No known hand-in deadline conflict.';},{min:c.selection.level,max:60,id:'turnin-level'});levels.append(labeled('Expected level at final hand-in',turnin),el('p','Grey threshold unverified: no non-grey guarantee.',{id:'turnin-risk'}));const overlap=el('div',null,{class:'overlaps'});for(const other of E.overlaps(d,c,D))overlap.append(btn(`${other.d.name} · ${other.d.plan.window.join('–')}`,()=>showChapter(other.d.id)));levels.append(overlap);if(w.earliestKnownPickup>p.window[1])levels.append(el('p','Full quest package unlocks after this planned window. Split preparation/visits rather than silently postponing neighboring dungeons.'));host.append(levels);
    host.append(el('h3','Level nearby'),el('p',p.hub[c.selection.faction]),el('p',c.selection.level<p.window[0]?`Use this hub for your remaining levels; reassess at ${p.window[0]} before adding more outdoor quests.`:'At or beyond the checkpoint: reduce optional filler and finish preparation first.',{class:'muted'}));
    if(p.wingPlans){const wings=details('Separate wing checkpoints','wings-'+d.id);wings.open=true;for(const wing of p.wingPlans){wings.append(el('h3',`${wing.name} · ${wing.window.join('–')}`),el('p',wing.reason),el('p','Relevant quest IDs: '+wing.questIds.filter(id=>r.quests.some(q=>q.id===id)).join(', ')));}host.append(wings);}
    host.append(el('h3','Before you go'));stepList(host,p.circuit,c.selection.faction.toLowerCase()+'-'+d.id+'-prep');
    const objectives=details('Inside order & return circuit','inside-'+d.id);stepList(objectives,p.inside,c.selection.faction.toLowerCase()+'-'+d.id+'-inside');objectives.append(el('h3','After the run'));stepList(objectives,p.after,c.selection.faction.toLowerCase()+'-'+d.id+'-after');objectives.append(el('p',p.feasibility));if(p.visits)objectives.append(el('p','Planned sections/visits: '+p.visits.join(' → ')));if(p.revisit)objectives.append(el('p',p.revisit==='outside-return'?'Return to the same instance where possible. Cleared objectives may require repeating content; do not reset without checking.':'A reset/re-clear may be necessary for newly unlocked objectives or missing drops.'));const visit=el('input',null,{type:'checkbox'});visit.checked=!!c.visits[d.id];visit.addEventListener('change',()=>update(c=>{c.visits[d.id]=visit.checked;return c;}));const vl=el('label');vl.style.flexDirection='row';vl.append(visit,el('span','Dungeon visit recorded—does not complete any quests'));objectives.append(vl);host.append(objectives);renderTravel(host,d);
    const qs=details(`Quest checklist · ${r.quests.length} records including chains`,'quests-'+d.id);if(r.quests.length<=10)qs.open=true;for(const q of r.quests.slice().sort((a,b)=>(a.role==='prerequisite'?-1:0)-(b.role==='prerequisite'?-1:0)||(a.minLevel??99)-(b.minLevel??99)||a.id-b.id))qs.append(questRow(q));if(!r.quests.length)qs.append(el('p','No character-eligible quest IDs are mapped yet. This is a coverage gap, not a quest-free dungeon.'));host.append(qs);
    if(d.observedGaps.length){const gaps=details(`Unmapped beta records · ${d.observedGaps.length}`,'gaps-'+d.id);const list=el('ul');d.observedGaps.forEach(g=>list.append(el('li',`${g.name} · quest level ${g.questLevel??'?'} — ${g.reason}`)));gaps.append(list);host.append(gaps);}
    if(r.missing.length>1||r.unknown.length){const blockers=details(`Readiness detail · ${r.missing.length} preparation checks`,'blockers-'+d.id);const list=el('ul');[...r.missing,...r.unknown].forEach(x=>list.append(el('li',x)));blockers.append(list);host.append(blockers);}
  }
  function renderCoverage(){const c=current(),cov=E.coverage(c,D),host=$('coverage-body');host.replaceChildren(el('p','Counts cover this bundled inventory—not every quest that may exist in Forever. Repeatables count once. Exclusions remain visible; skipped quests never count complete.'));const tools=el('div',null,{class:'coverage-tools'});tools.append(labeled('Show',selectControl(['all','routed','completed','unresolved','excluded'],coverageFilter,v=>{coverageFilter=v;renderCoverage();},'coverage-filter')));host.append(tools);for(const row of cov.rows.filter(r=>coverageFilter==='all'||r.status===coverageFilter)){const div=el('div',null,{class:'coverage-row'});div.append(el('span',`${row.q.name} #${row.q.id}`),el('span',row.status),el('small',row.reason));host.append(div);}host.append(el('h3','Unmapped / unverified content'));for(const g of D.gaps)host.append(el('p',g));D.observedGaps.forEach(g=>host.append(el('p',`${D.dungeons.find(d=>d.id===g.dungeon)?.name}: ${g.name} — ${g.reason}`)));for(const d of D.dungeons.filter(d=>!d.questIds.length))host.append(el('p',d.name+': no quest-ID inventory yet.'));const review=E.review(c,D);if(review.orphaned.length)host.append(el('p',`Preserved historical quest IDs no longer in this inventory: ${review.orphaned.join(', ')}. Their progress was not deleted.`));}
  function renderEvidence(){const h=$('evidence-body');h.replaceChildren(el('p',`Data ${D.dataVersion} · routes ${D.routeVersion} · progress format ${E.PROGRESS_VERSION}. ${D.build}.`),el('p','Verified describes an inspected field/record, not an entire route. Coordinates and most pickup/eligibility data are provisional. Classic comments and guide fallbacks are never silently treated as observed beta behavior.'),el('p','Grey-rule verification is outstanding. One-clear feasibility is conditional on accepted quests, required drops and chain order. No exact XP pace or global travel optimum is claimed.'),el('p','Hearthstone: 60-minute cooldown in the inspected Forever spell record; no cooldown-reduction perks assumed. Quest-log size is editable. Personal class shortcuts are not routed until verified.'));for(const s of Object.values(D.sources)){const p=el('p');p.append(el('a',s.title,{href:s.url,target:'_blank',rel:'noopener'}),document.createTextNode(` · ${s.date} · ${s.confidence}`));h.append(p);}h.append(el('p','Factual IDs and location data were audited locally. Travel instructions are original. No source addon code, database requests, account access or game-log integration runs in this page.'));}
  function render(){const open=new Set([...document.querySelectorAll('details[data-key][open]')].map(n=>n.dataset.key));const c=current();$('characters').replaceChildren(...library.characters.map(c=>option(c.id,c.name)));$('characters').value=c.id;const rev=E.review(c,D);$('review-banner').hidden=!rev.changed;if(rev.changed){$('review-banner').replaceChildren(el('span','Quest/route data changed. Completion history is preserved; review changed instructions before continuing. '),btn('Acknowledge data update',()=>update(c=>{c.reviewedDataVersion=D.dataVersion;c.reviewedRouteVersion=D.routeVersion;return c;})));}renderOverview();renderChapters();renderMobileChapters();renderChapter();renderCoverage();renderEvidence();for(const d of document.querySelectorAll('details[data-key]'))if(open.has(d.dataset.key))d.open=true;}
  function fillRaces(){const faction=$('faction').value,old=$('race').value;$('race').replaceChildren(...E.RACES[faction].map(x=>option(x,x)));if(E.RACES[faction].includes(old))$('race').value=old;}
  function setup(isNew){creating=isNew;const c=current();$('character-name').value=isNew?'':c.name;$('faction').value=c.selection.faction;fillRaces();$('race').value=c.selection.race;$('game-class').value=c.selection.class;$('level').value=isNew?1:c.selection.level;for(const box of $('professions').querySelectorAll('input'))box.checked=!isNew&&c.selection.professions.includes(box.value);$('setup').hidden=false;$('edit-character').setAttribute('aria-expanded','true');$('character-name').focus();}
  $('game-class').append(...Object.keys(E.CLASSES).map(x=>option(x,x)));for(const p of E.PROFESSIONS){const l=el('label'),i=el('input',null,{type:'checkbox',value:p});l.append(i,el('span',p));$('professions').append(l);}
  $('faction').addEventListener('change',fillRaces);$('new-character').addEventListener('click',()=>setup(true));$('edit-character').addEventListener('click',()=>setup(false));$('cancel-setup').addEventListener('click',()=>{$('setup').hidden=true;$('edit-character').setAttribute('aria-expanded','false');});
  $('setup').addEventListener('submit',event=>{event.preventDefault();try{const n=E.name($('character-name').value),s=E.selection({faction:$('faction').value,race:$('race').value,class:$('game-class').value,level:$('level').value,professions:[...$('professions').querySelectorAll('input:checked')].map(i=>i.value)});if(library.characters.some(c=>c.name.toLowerCase()===n.toLowerCase()&&(creating||c.id!==library.activeId)))throw Error('That character name is already saved. Choose a different name.');if(creating){const c=E.character('character-'+Date.now(),n,s,D.dataVersion,D.routeVersion);library.characters.push(c);library.activeId=c.id;chapterId='start';}else{current().name=n;current().selection=s;}save();$('setup').hidden=true;$('edit-character').setAttribute('aria-expanded','false');say('Character saved. Existing quest history is unchanged.');render();}catch(e){say(e.message,true);}});
  $('characters').addEventListener('change',()=>{library.activeId=$('characters').value;chapterId='start';$('setup').hidden=true;save();render();});$('chapter-filter').addEventListener('input',renderChapters);
  $('export-progress').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({...library,exportedDataVersion:D.dataVersion,routeVersion:D.routeVersion},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a',null,{href:url,download:'forever-leveling-progress.json'});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);say('Exported all local characters, including names and private progress. Route links do not include those.');});
  $('import-button').addEventListener('click',()=>$('import-progress').click());
  $('import-progress').addEventListener('change',async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>2000000)throw Error('Choose a progress file smaller than 2 MB.');const imported=E.importLibrary(await file.text());const merged=JSON.parse(JSON.stringify(library));for(const c of imported.characters){const old=merged.characters.find(x=>x.id===c.id);if(old&&JSON.stringify(old)===JSON.stringify(c))continue;let copy=JSON.parse(JSON.stringify(c));if(merged.characters.some(x=>x.id===copy.id))copy.id='import-'+Date.now()+'-'+merged.characters.length;const base=copy.name;let i=2;while(merged.characters.some(x=>x.name.toLowerCase()===copy.name.toLowerCase()))copy.name=base.slice(0,64)+` (import ${i++})`;merged.characters.push(copy);merged.activeId=copy.id;}if(merged.characters.length>100)throw Error('Import would exceed 100 characters.');library=E.importLibrary(JSON.stringify(merged));save();chapterId='start';render();say('Imported as separate records where names or IDs conflicted. Existing progress was preserved.');}catch(e){say('Import not applied: '+e.message,true);}finally{event.target.value='';}});
  $('share-route').addEventListener('click',()=>{const url=new URL('leveling.html',location.href);url.search=E.routeParams(current(),chapterId);url.hash='';$('share-link').value=url.href;$('share-box').hidden=false;$('share-link').focus();$('share-link').select();});
  $('mobile-chapter').addEventListener('change',()=>showChapter($('mobile-chapter').value));
  render();save();
})();
