(function (root, factory) {
  const value = factory();
  if (typeof module === 'object' && module.exports) module.exports = value;
  root.FOREVER_RAID_DATA = value;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  const buffs = {
    mark: { name: 'Mark of the Wild', scope: 'raid', helps: 'all', status: 'confirmed', note: 'Baseline Druid buff; targeted and maintainable across the raid. Improved Mark of the Wild is baseline in Forever.', evidence: 'https://www.wowhead.com/forever/spell=9885/mark-of-the-wild' },
    fortitude: { name: 'Power Word: Fortitude', scope: 'raid', helps: 'all', status: 'confirmed', note: 'Baseline Priest buff; targeted and maintainable across the raid.', evidence: 'https://www.wowhead.com/forever/spell=2791/power-word-fortitude' },
    spirit: { name: 'Divine Spirit', scope: 'raid', helps: 'mana', status: 'confirmed', note: 'Forever makes the former talent effect baseline for Priests. Feral Druids now benefit because Shifting Power is mana-intensive and they receive natural mana regeneration while shifted.', evidence: 'https://worldofwarcraft.blizzard.com/en-us/news/24303313' },
    intellect: { name: 'Arcane Intellect', scope: 'raid', helps: 'mana', status: 'confirmed', note: 'Baseline Mage buff; targeted and maintainable across the raid. Feral Druids now benefit because Shifting Power makes their mana pool relevant.', evidence: 'https://www.wowhead.com/forever/spell=1461/arcane-intellect' },
    kings: { name: 'Blessing of Kings', scope: 'raid', helps: 'all', status: 'confirmed', providerExclusive: 'paladin-blessing', note: 'Baseline in Forever. One Blessing from each Paladin can be active on a recipient, so multiple Paladins are needed to stack Kings with other Blessings on the same player.', evidence: 'https://www.wowhead.com/forever/spell=20217/blessing-of-kings' },
    might: { name: 'Blessing of Might', scope: 'raid', helps: 'melee', status: 'confirmed', providerExclusive: 'paladin-blessing', note: 'Melee attack power. One Blessing from each Paladin can be active on a recipient.', evidence: 'https://www.wowhead.com/forever/spell=19740/blessing-of-might' },
    wisdom: { name: 'Blessing of Wisdom', scope: 'raid', helps: 'manaRegen', status: 'confirmed', providerExclusive: 'paladin-blessing', note: 'Mana regeneration. Feral Druids now benefit because Shifting Power makes mana regeneration useful to them. One Blessing from each Paladin can be active on a recipient.', evidence: 'https://www.wowhead.com/forever/spell=19742/blessing-of-wisdom' },
    salvation: { name: 'Blessing of Salvation', scope: 'raid', helps: 'nonTank', status: 'confirmed', providerExclusive: 'paladin-blessing', note: 'Trained Paladin Blessing at level 26. Reduces all threat generated by 30% for 1 hour. Useful to damage dealers and healers; tanks are intentionally excluded. One Blessing from each Paladin can be active on a recipient.', evidence: 'https://www.wowhead.com/forever/spell=1038/blessing-of-salvation' },
    battleShout: { name: 'Battle Shout', scope: 'party', helps: 'melee', status: 'confirmed', note: 'Baseline Warrior party buff: melee attack power to party members in range.', evidence: 'https://www.wowhead.com/forever/spell=6192/battle-shout' },
    moonkin: { name: 'Moonkin Aura', scope: 'party', helps: 'all', status: 'confirmed', exclusive: ['druid-crit'], note: 'Balance talent. While in Moonkin Form, all party members in range gain 3% critical chance. Exclusive with Leader of the Pack.', evidence: 'https://www.wowhead.com/forever/spell=24858/moonkin-form' },
    leader: { name: 'Leader of the Pack', scope: 'party', helps: 'all', status: 'confirmed', exclusive: ['druid-crit'], note: 'Feral talent. While in Cat, Bear, or Dire Bear Form, all party members in range gain 3% critical chance. Exclusive with Moonkin Aura.', evidence: 'https://www.wowhead.com/forever/spell=17007/leader-of-the-pack' },
    trueshot: { name: 'Trueshot Aura', scope: 'party', helps: 'rangedPhysical', status: 'confirmed', note: 'Forever trains this Hunter party aura at level 32; it is not Marksmanship-only. It grants ranged attack power to party members in range.', evidence: 'https://www.wowhead.com/forever/spell=1299348/trueshot-aura' },
    vampiric: { name: 'Vampiric Embrace', scope: 'party', helps: 'all', status: 'confirmed', note: 'Shadow talent and 30-second effect on a 1-minute cooldown. Shadow damage heals the Priest’s party; this is not an always-on stat buff.', evidence: 'https://www.wowhead.com/forever/spell=15286/vampiric-embrace' },
    windfury: { name: 'Windfury Totem', scope: 'party', helps: 'melee', status: 'confirmed', exclusive: ['air-totem'], note: 'Baseline Shaman party weapon enhancement. Competes with Grace of Air and Tranquil Air for the Air Totem slot; a Shaman can still keep a personal Flametongue Weapon enchant.', evidence: 'https://www.wowhead.com/forever/spell=8512/windfury-totem' },
    grace: { name: 'Grace of Air Totem', scope: 'party', helps: 'physical', status: 'confirmed', exclusive: ['air-totem'], note: 'Baseline Shaman party Agility effect. Competes with Windfury and Tranquil Air in the same group.', evidence: 'https://www.wowhead.com/forever/spell=25359/grace-of-air-totem' },
    tranquil: { name: 'Tranquil Air Totem', scope: 'party', helps: 'all', status: 'confirmed', exclusive: ['air-totem'], note: 'Baseline Shaman party threat reduction. Competes with Windfury and Grace of Air in the same group.', evidence: 'https://www.wowhead.com/forever/spell=25908/tranquil-air-totem' },
    strength: { name: 'Strength of Earth Totem', scope: 'party', helps: 'melee', status: 'confirmed', note: 'Baseline Shaman party Strength effect.', evidence: 'https://www.wowhead.com/forever/spell=25361/strength-of-earth-totem' },
    manaSpring: { name: 'Mana Spring Totem', scope: 'party', helps: 'manaRegen', status: 'confirmed', note: 'Baseline Shaman party mana regeneration effect. Feral Druids now benefit because Shifting Power makes mana regeneration useful to them.', evidence: 'https://www.wowhead.com/forever/spell=10496/mana-spring-totem' },
    manaTide: { name: 'Mana Tide Totem', scope: 'party', helps: 'manaRegen', status: 'confirmed', note: 'Restoration talent and 5-minute cooldown; restores mana to group members in range. Feral Druids can benefit through Shifting Power.', evidence: 'https://www.wowhead.com/forever/spell=17359/mana-tide-totem' },
    flametongue: { name: 'Flametongue Totem', scope: 'party', helps: 'melee', status: 'confirmed', note: 'Baseline Shaman Fire Totem weapon enhancement. It can be dropped alongside an Air Totem, while a Shaman may instead use the personal Flametongue Weapon enchant.', evidence: 'https://www.wowhead.com/forever/spell=16387/flametongue-totem' },
    sanctity: { name: 'Sanctity Aura', scope: 'party', helps: 'holy', status: 'unresolved', note: 'Legacy spell data exists, but the current Forever Paladin talent calculator does not expose Sanctity Aura as a learnable talent. Excluded from coverage pending playable-beta confirmation.', evidence: 'https://www.wowhead.com/forever/talent-calc/paladin' },
    sunder: { name: 'Sunder Armor', scope: 'boss', helps: 'physical', status: 'confirmed', exclusive: ['major-armor'], note: 'Baseline Warrior armor reduction, stacking to five applications. It does not stack with Expose Armor.', evidence: 'https://www.wowhead.com/forever/spell=11597/sunder-armor' },
    expose: { name: 'Expose Armor', scope: 'boss', helps: 'physical', status: 'confirmed', exclusive: ['major-armor'], note: 'Baseline Rogue finishing move and alternative to Sunder Armor. Improved Expose Armor is a talent, but the base debuff is available to every Rogue.', evidence: 'https://www.wowhead.com/forever/spell=8647/expose-armor' },
    faerie: { name: 'Faerie Fire', scope: 'boss', helps: 'physical', status: 'confirmed', note: 'Baseline Druid armor reduction / anti-stealth debuff. All Druid specializations can maintain the caster version; Feral can also talent into its form-compatible version. Preferred over Curse of Recklessness for the shared physical-armor support requirement.', evidence: 'https://www.wowhead.com/forever/spell=9907/faerie-fire' },
    huntersMark: { name: 'Hunter’s Mark', scope: 'boss', helps: 'rangedPhysical', status: 'confirmed', note: 'Baseline Hunter debuff that increases ranged attack power against the marked target for all attackers.', evidence: 'https://www.wowhead.com/forever/spell=1130/hunters-mark' },
    curseElements: { name: 'Curse of the Elements', scope: 'boss', helps: 'magicDamage', status: 'confirmed', providerExclusive: 'warlock-curse', note: 'Baseline Warlock curse: increases all magic damage taken. Each Warlock can maintain only one curse on the target.', evidence: 'https://www.wowhead.com/forever/spell=1490/curse-of-the-elements' },
    curseRecklessness: { name: 'Curse of Recklessness', scope: 'boss', helps: 'physical', status: 'confirmed', providerExclusive: 'warlock-curse', note: 'Baseline Warlock curse: reduces armor but increases the target’s melee attack power. It is the fallback for the shared physical-armor support requirement when Faerie Fire is unavailable. Each Warlock can maintain only one curse on the target.', evidence: 'https://www.wowhead.com/forever/spell=7658/curse-of-recklessness' },
    insectSwarm: { name: 'Insect Swarm', scope: 'boss', helps: 'tank', status: 'confirmed', note: 'Baseline Druid debuff in Forever. Preferred for the shared boss-mitigation row when both it and Scorpid Sting are available.', evidence: 'https://www.wowhead.com/forever/spell=24975/insect-swarm' },
    scorpidSting: { name: 'Scorpid Sting', scope: 'boss', helps: 'tank', status: 'confirmed', note: 'Baseline Hunter sting and the fallback for the shared boss-mitigation row when Insect Swarm is unavailable. Only one Sting per Hunter can be active on a target.', evidence: 'https://www.wowhead.com/forever/spell=14275/scorpid-sting' },
    attackPowerReduction: { name: 'Attack Power Reduction', scope: 'boss', helps: 'tank', status: 'confirmed', note: 'One shared melee-attack-power reduction category. Warriors use Demoralizing Shout, Feral Druids use Demoralizing Roar, and expected Retribution or Protection Paladin raid builds may talent Vindication through the Retribution tree. These equivalent effects do not add together; use the strongest available rank/talent.', evidence: 'https://worldofwarcraft.blizzard.com/en-us/news/24303313', providerVariants: {
      warrior: { name: 'Demoralizing Shout', icon: 'effect-icons/demoShout.jpg', detail: 'Baseline Warrior ability.' },
      druid: { name: 'Demoralizing Roar', icon: 'effect-icons/demoRoar.jpg', detail: 'Baseline Druid ability used in Bear Form; modeled on the Feral raid spec.' },
      paladin: { name: 'Vindication', icon: 'effect-icons/vindication.jpg', detail: 'Retribution-tree talent; expected Retribution and Protection raid builds can take it.' }
    } },
    thunderClap: { name: 'Thunder Clap', scope: 'boss', helps: 'tank', status: 'confirmed', note: 'Baseline Warrior attack-speed reduction. Forever’s level-58 rank is usable in Battle or Defensive Stance.', evidence: 'https://www.wowhead.com/forever/spell=11581/thunder-clap' }
  };
  for (const buff of Object.values(buffs)) buff.confidence = buff.status === 'confirmed' ? 'verified' : 'unresolved';
  for (const [id, buff] of Object.entries(buffs)) buff.icon = `effect-icons/${id}.jpg`;

  const classes = [
    ['warrior', 'Warrior', '#c79c6e', [['arms','Arms','damage',['battleShout','sunder','attackPowerReduction','thunderClap']],['fury','Fury','damage',['battleShout','sunder','attackPowerReduction','thunderClap']],['protection','Protection','tank',['battleShout','sunder','attackPowerReduction','thunderClap']]]],
    ['paladin', 'Paladin', '#f58cba', [['holy','Holy','healer',['kings','might','wisdom','salvation']],['protection','Protection','tank',['kings','might','wisdom','salvation','attackPowerReduction']],['retribution','Retribution','damage',['kings','might','wisdom','salvation','attackPowerReduction']]]],
    ['hunter', 'Hunter', '#abd473', [['beast-mastery','Beast Mastery','damage',['huntersMark','trueshot','scorpidSting'],{ roleLabel: 'Ranged Damage' }],['marksmanship','Marksmanship','damage',['huntersMark','trueshot','scorpidSting'],{ roleLabel: 'Ranged Damage' }],['survival','Survival','damage',['huntersMark','trueshot','scorpidSting'],{ roleLabel: 'Melee Damage' }]]],
    ['rogue', 'Rogue', '#fff569', [['assassination','Assassination','damage',['expose']],['combat','Combat','damage',['expose']],['subtlety','Subtlety','damage',['expose']]]],
    ['priest', 'Priest', '#f3f3f3', [['discipline','Discipline','healer',['fortitude','spirit']],['holy','Holy','healer',['fortitude','spirit']],['shadow','Shadow','damage',['fortitude','spirit','vampiric']]]],
    ['shaman', 'Shaman', '#0070de', [['elemental','Elemental','damage',['strength','windfury','grace','tranquil','manaSpring','flametongue']],['enhancement','Enhancement','damage',['strength','windfury','grace','tranquil','manaSpring','flametongue']],['restoration','Restoration','healer',['strength','windfury','grace','tranquil','manaSpring','flametongue','manaTide']]]],
    ['mage', 'Mage', '#69ccf0', [['arcane','Arcane','damage',['intellect']],['fire','Fire','damage',['intellect']],['frost','Frost','damage',['intellect']]]],
    ['warlock', 'Warlock', '#9482c9', [['affliction','Affliction','damage',['curseElements','curseRecklessness']],['demonology','Demonology','damage',['curseElements','curseRecklessness']],['destruction','Destruction','damage',['curseElements','curseRecklessness']]]],
    ['druid', 'Druid', '#ff7d0a', [['balance','Balance','damage',['mark','moonkin','faerie','insectSwarm']],['feral','Feral','hybrid',['mark','leader','faerie','attackPowerReduction'],{ roleLabel: 'Damage / Tank', forms: ['cat','bear'] }],['restoration','Restoration','healer',['mark','faerie','insectSwarm']]]]
  ];
  const roleProfiles = {
    tank: ['physical','melee','tank'], healer: ['mana','spell'],
    damage: [],
    'warrior:arms': ['physical','melee'], 'warrior:fury': ['physical','melee'],
    'paladin:holy': ['mana','spell','holy'], 'paladin:protection': ['physical','melee','mana','holy','magicDamage'],
    'paladin:retribution': ['physical','melee','mana','holy','magicDamage'], 'hunter:beast-mastery': ['physical','rangedPhysical','mana'],
    'hunter:marksmanship': ['physical','rangedPhysical','mana'], 'hunter:survival': ['physical','melee','mana'],
    'rogue:assassination': ['physical','melee'], 'rogue:combat': ['physical','melee'], 'rogue:subtlety': ['physical','melee'],
    'priest:shadow': ['mana','spell','shadowArcane','magicDamage'], 'shaman:elemental': ['mana','spell','magicDamage'], 'shaman:enhancement': ['physical','melee','mana','magicDamage'],
    'mage:arcane': ['mana','spell','shadowArcane','magicDamage'], 'mage:fire': ['mana','spell','fireFrost','magicDamage'], 'mage:frost': ['mana','spell','fireFrost','magicDamage'],
    'warlock:affliction': ['mana','spell','shadowArcane','magicDamage'], 'warlock:demonology': ['mana','spell','shadowArcane','magicDamage'], 'warlock:destruction': ['mana','spell','fireFrost','shadowArcane','magicDamage'],
    'druid:balance': ['mana','spell','magicDamage'], 'druid:feral': ['physical','melee','mana'], 'druid:restoration': ['magicDamage']
  };
  const magicDamageClasses = new Set(['paladin','hunter','rogue','priest','shaman','mage','warlock']);
  const specs = classes.flatMap(([classId, className, color, entries]) => entries.map(([specId, name, role, provides, metadata = {}]) => {
    const tags = [...new Set(['all', ...(role !== 'tank' ? ['nonTank'] : []), ...(roleProfiles[role] || []), ...(roleProfiles[`${classId}:${specId}`] || []), ...(magicDamageClasses.has(classId) ? ['magicDamage'] : []), ...(role !== 'damage' && classId !== 'warrior' && classId !== 'druid' ? ['mana'] : [])])];
    if (tags.includes('mana')) tags.push('manaRegen');
    return { id: `${classId}:${specId}`, classId, className, name, role, color, icon: `spec-icons/${classId}-${specId}.jpg`, provides, ...metadata, tags: [...new Set(tags)] };
  }));
  return {
    version: '2026-10-03-beta-audit-6', groupSize: 5, raidSizes: [5, 10, 20, 40], buffs, specs,
    blessingIds: ['kings','might','wisdom','salvation'],
    legacySpecIds: { 'druid:feral-cat': 'druid:feral', 'druid:feral-bear': 'druid:feral' },
    recommended: { raid: ['mark','fortitude','spirit','intellect','kings','might','wisdom','salvation'] },
    providerAssignmentTargets: { 'paladin-blessing': 3 },
    bossRecommendations: [
      { id: 'major-armor', name: 'Sunder Armor', effects: ['sunder','expose'], always: true, iconEffect: 'sunder', preferWhenCovered: ['expose','sunder'] },
      { id: 'faerie', name: 'Faerie Fire', effects: ['faerie','curseRecklessness'], always: true, iconEffect: 'faerie', preferWhenCovered: ['faerie','curseRecklessness'] },
      { id: 'boss-mitigation', name: 'Insect Swarm', effects: ['insectSwarm','scorpidSting'], always: true, iconEffect: 'insectSwarm', preferWhenCovered: ['insectSwarm','scorpidSting'] },
      { id: 'hunters-mark', name: 'Hunter’s Mark', effects: ['huntersMark'], requiresClass: 'hunter' },
      { id: 'curse-elements', name: 'Curse of the Elements', effects: ['curseElements'], helps: 'magicDamage' },
      { id: 'attack-power-reduction', name: 'Demoralizing Shout', effects: ['attackPowerReduction'], always: true, defaultProviderClass: 'warrior', providerDisplayPriority: ['warrior','druid','paladin'] },
      { id: 'attack-speed-reduction', name: 'Thunder Clap', effects: ['thunderClap'], always: true }
    ],
    partyRecommendations: [
      { id: 'melee-ap', name: 'Melee attack power', helps: 'melee', effects: ['battleShout'] },
      { id: 'druid-crit', name: 'Critical chance aura', helps: 'all', effects: ['moonkin','leader'], recipientIcon: { physical: 'leader', spell: 'moonkin', mixed: 'leader' } },
      { id: 'ranged-ap', name: 'Ranged attack power', helps: 'rangedPhysical', effects: ['trueshot'] },
      { id: 'strength', name: 'Strength', helps: 'melee', effects: ['strength'] },
      { id: 'air-totem', name: 'Air totem', showOptions: true, options: [
        { id: 'windfury', helps: 'melee' },
        { id: 'grace', helps: 'physical' }
      ] },
      { id: 'mana-regen', name: 'Mana regeneration', helps: 'manaRegen', effects: ['manaSpring'] }
    ],
    groupChoiceLabels: {
      'air-totem': 'Air Totem'
    },
    groupEffectPriority: {
      'druid-crit': ['moonkin', 'leader']
    },
    optionalGroupEffects: [
      { id: 'paladin-auras', classId: 'paladin', name: 'Paladin auras', options: ['Devotion Aura', 'Retribution Aura', 'Concentration Aura'] }
    ],
    campBuffs: [
      { id: 'mana-well', name: 'Mana Well', profession: 'Alchemy', covers: ['wisdom'], preferCamp: true, evidence: 'https://www.wowhead.com/forever/item=279956/mana-well' },
      { id: 'sharpening-wheel', name: 'Sharpening Wheel', profession: 'Blacksmithing', covers: ['strength'], preferCamp: true, evidence: 'https://www.wowhead.com/forever/item=279944/sharpening-wheel' },
      { id: 'enchanted-lute', name: 'Enchanted Lute', profession: 'Enchanting', covers: ['mark'], warnWhenCovered: true, evidence: 'https://www.wowhead.com/forever/item=279976/enchanted-lute' },
      { id: 'incense-candle', name: 'Incense Candle', profession: 'Herbalism', covers: ['intellect'], warnWhenCovered: true, evidence: 'https://www.wowhead.com/forever/item=279962/incense-candle' },
      { id: 'lodestone', name: 'Lodestone', profession: 'Mining', covers: ['might'], preferCamp: true, evidence: 'https://www.wowhead.com/forever/item=279960/lodestone' },
      { id: 'camp-chair', name: 'Camp Chair', profession: 'Skinning', covers: ['moonkin', 'leader'], warnWhenCovered: true, evidence: 'https://www.wowhead.com/forever/item=279979/camp-chair' },
      { id: 'faction-banner', name: 'Faction Banner', profession: 'Tailoring', covers: ['spirit'], warnWhenCovered: true, evidence: 'https://www.wowhead.com/forever/item=279972/faction-banner' },
      { id: 'first-aid-kit', name: 'First Aid Kit', profession: 'First Aid', covers: ['fortitude'], warnWhenCovered: true, evidence: 'https://www.wowhead.com/forever/item=279968/first-aid-kit' },
      { id: 'fish-bowl', name: 'Fish Bowl', profession: 'Fishing', covers: ['kings'], preferCamp: true, evidence: 'https://www.wowhead.com/forever/item=279967/fish-bowl' }
    ],
    sources: [
      { label: 'Blizzard — Forever beta development notes (Sep 24)', url: 'https://us.forums.blizzard.com/en/wow/t/wow-forever-beta-development-notes-%E2%80%93-updated-september-24/2360696' },
      { label: 'Blizzard — Forever Deep Dive (baseline class buffs and Vindication)', url: 'https://worldofwarcraft.blizzard.com/en-us/news/24303313' },
      { label: 'Blizzard — Forever What’s Next (10- and 20-player raids)', url: 'https://worldofwarcraft.blizzard.com/en-us/news/24303862/world-of-warcraft-forever-whats-next-panel-recap' },
      { label: 'Forever raid-comp research summary', url: 'https://classicwow.gg/forever/guides/raid-comp' }
    ]
  };
});
